[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/containerd/containerd"
  version = "1.2.1"

[[constraint]]
  name = "github.com/opencontainers/go-digest"
  version = "1.0.0-rc1"

[[constraint]]
  name = "github.com/opencontainers/image-spec"
  version = "1.0.1"
